- name: Web server uninstall
  become: yes
  hosts: nodes
  gather_facts: false

  tasks:
    - name: Httpd uninstall
      yum: name=httpd state=absent

    - name: Delete index.html
      file:
        path: /var/www/html/index.html
        state: absent
      
    - name: Disable traffic http
      firewalld:
        service: http
        permanent: yes
        immediate: yes
        state: disabled
